### ISSUE TITLE
Возможно, неверное описание задания

### ISSUE THREAD

**Issue by alexlogan** [dstuit/git-lab1#5]
В задании к  лабораторной работе №1 по git
 
Задание 1

>* Установите Git на свой компьютер
* Создайте папку, в которой разместите свой проект
* Инициализируйте в этой папке репозиторий (используя команду git init)
* Создайте в папке текстовый файл README.md, который будет содержать следующую информацию: ваше имя, группа, номер и название лабораторной
* Выполните команду git status, объясните результат
* **Добавьте файл README.md в индекс с помощью команды ~~git commit~~ _(возможно имелось в виду git add README.md)_**

**Comment by dstuit** [comment]
Да, нужно исправить, спасибо.
